# Continuous Integration with https://travis-ci.org/
language: cpp

# Use Ubuntu 14.04 - https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=clang++-3.7

script:
  - mkdir build
  - cd build
  - cmake .. && make

